#!/usr/bin/env python3
"""
knowledge-bridge: setup_vault.py
Creates the Obsidian vault folder structure for a new project.

Usage: python setup_vault.py <vault_path> <project_name> [project_path]
"""

import sys
import json
import os
from datetime import date

def create_note(path: str, title: str, tags: list, content: str):
    """Write an Obsidian note with frontmatter."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    frontmatter = f"""---
title: "{title}"
created: "{date.today().isoformat()}"
tags: [{", ".join(tags)}]
source: knowledge-bridge init
---

"""
    with open(path, "w") as f:
        f.write(frontmatter + content)
    print(f"  Created: {path}")


def setup_vault(vault_path: str, project_name: str, project_path: str = ""):
    base = os.path.join(vault_path, "Projects", project_name)

    folders = [
        os.path.join(base, "Research"),
        os.path.join(base, "Specs"),
        os.path.join(base, "Modules"),
        os.path.join(base, "Daily"),
    ]
    for folder in folders:
        os.makedirs(folder, exist_ok=True)
        print(f"  Created folder: {folder}")

    create_note(
        path=os.path.join(base, "Project Overview.md"),
        title=f"{project_name} — Project Overview",
        tags=["project", "overview"],
        content=f"""# {project_name}

## Purpose
> Describe what this project does in 1-2 sentences.

## Tech Stack
- Language:
- Framework:
- Database:

## Key Links
- VSCode Project: `{project_path or "add path here"}`
- Repository:

## Architecture
> Add a high-level architecture diagram or description here.

## Important Notes
> Decision log, caveats, known issues.

## Navigation
- [[File Map]] — full directory tree
- [[Open Questions]] — unresolved decisions
- [[Dependency Graph]] — library map
- [Research/](Research/) — NotebookLM imports
- [Specs/](Specs/) — feature specifications
- [Modules/](Modules/) — code module notes
""",
    )

    create_note(
        path=os.path.join(base, "File Map.md"),
        title=f"{project_name} — File Map",
        tags=["code", "map"],
        content=f"""# File Map

> Auto-generated by knowledge-bridge. Run sync to update.

## Project Root
```
{project_path or "(project path not set)"}
```

## Directory Tree
> Run: `claude 'knowledge-bridge: update file map'` to populate this.

## Entry Points
> Main files / entry points will appear here after sync.
""",
    )

    create_note(
        path=os.path.join(base, "Open Questions.md"),
        title=f"{project_name} — Open Questions",
        tags=["question", "todo"],
        content=f"""# Open Questions

> Unresolved design decisions, TODOs, and things to figure out.

## Architecture
- [ ]

## Implementation
- [ ]

## Research Needed
- [ ]

## Auto-extracted TODOs
> Run: `claude 'knowledge-bridge: extract todos'` to populate from code.
""",
    )

    create_note(
        path=os.path.join(base, "Dependency Graph.md"),
        title=f"{project_name} — Dependency Graph",
        tags=["code", "dependencies"],
        content=f"""# Dependency Graph

> Key libraries and how they're used.

## External Dependencies

| Package | Version | Purpose |
|---------|---------|---------|
| | | |

## Internal Module Map

```mermaid
graph TD
    A[Entry Point] --> B[Module A]
    A --> C[Module B]
```

> Run: `claude 'knowledge-bridge: rebuild dependency graph'` to update.
""",
    )

    config = {
        "vault_path": vault_path,
        "project_path": project_path,
        "project_name": project_name,
        "bridge_folder": f"Projects/{project_name}",
        "last_sync": date.today().isoformat(),
        "version": "1.0"
    }
    config_path = os.path.join(project_path, ".knowledge-bridge.json") if project_path else ".knowledge-bridge.json"
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)
    print(f"  Config saved: {config_path}")

    print(f"\nVault initialized for '{project_name}'")
    print(f"   Open in Obsidian: obsidian://open?vault={os.path.basename(vault_path)}&file=Projects/{project_name}/Project%20Overview")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python setup_vault.py <vault_path> <project_name> [project_path]")
        sys.exit(1)
    vault_path = sys.argv[1]
    project_name = sys.argv[2]
    project_path = sys.argv[3] if len(sys.argv) > 3 else ""
    setup_vault(vault_path, project_name, project_path)
